var namespace_cloud_once_1_1_internal =
[
    [ "Editor", "namespace_cloud_once_1_1_internal_1_1_editor.html", "namespace_cloud_once_1_1_internal_1_1_editor" ],
    [ "Providers", "namespace_cloud_once_1_1_internal_1_1_providers.html", "namespace_cloud_once_1_1_internal_1_1_providers" ],
    [ "Utils", "namespace_cloud_once_1_1_internal_1_1_utils.html", "namespace_cloud_once_1_1_internal_1_1_utils" ],
    [ "AchievementsBridge", "class_cloud_once_1_1_internal_1_1_achievements_bridge.html", "class_cloud_once_1_1_internal_1_1_achievements_bridge" ],
    [ "CloudOnceEvents", "class_cloud_once_1_1_internal_1_1_cloud_once_events.html", "class_cloud_once_1_1_internal_1_1_cloud_once_events" ],
    [ "CloudProviderBase", "class_cloud_once_1_1_internal_1_1_cloud_provider_base.html", "class_cloud_once_1_1_internal_1_1_cloud_provider_base" ],
    [ "ConflictResolver", "class_cloud_once_1_1_internal_1_1_conflict_resolver.html", "class_cloud_once_1_1_internal_1_1_conflict_resolver" ],
    [ "CurrencyValue", "class_cloud_once_1_1_internal_1_1_currency_value.html", "class_cloud_once_1_1_internal_1_1_currency_value" ],
    [ "DataManager", "class_cloud_once_1_1_internal_1_1_data_manager.html", "class_cloud_once_1_1_internal_1_1_data_manager" ],
    [ "GameData", "class_cloud_once_1_1_internal_1_1_game_data.html", "class_cloud_once_1_1_internal_1_1_game_data" ],
    [ "iCloudBridge", "class_cloud_once_1_1_internal_1_1i_cloud_bridge.html", "class_cloud_once_1_1_internal_1_1i_cloud_bridge" ],
    [ "iCloudListener", "class_cloud_once_1_1_internal_1_1i_cloud_listener.html", null ],
    [ "IJsonConvertible", "interface_cloud_once_1_1_internal_1_1_i_json_convertible.html", null ],
    [ "IJsonDeserializable", "interface_cloud_once_1_1_internal_1_1_i_json_deserializable.html", "interface_cloud_once_1_1_internal_1_1_i_json_deserializable" ],
    [ "IJsonSerializable", "interface_cloud_once_1_1_internal_1_1_i_json_serializable.html", "interface_cloud_once_1_1_internal_1_1_i_json_serializable" ],
    [ "IPersistent", "interface_cloud_once_1_1_internal_1_1_i_persistent.html", "interface_cloud_once_1_1_internal_1_1_i_persistent" ],
    [ "JsonHelper", "class_cloud_once_1_1_internal_1_1_json_helper.html", "class_cloud_once_1_1_internal_1_1_json_helper" ],
    [ "JSONObject", "class_cloud_once_1_1_internal_1_1_j_s_o_n_object.html", "class_cloud_once_1_1_internal_1_1_j_s_o_n_object" ],
    [ "PersistentCurrency", "class_cloud_once_1_1_internal_1_1_persistent_currency.html", "class_cloud_once_1_1_internal_1_1_persistent_currency" ],
    [ "PersistentValue", "class_cloud_once_1_1_internal_1_1_persistent_value.html", "class_cloud_once_1_1_internal_1_1_persistent_value" ],
    [ "SyncableCurrency", "class_cloud_once_1_1_internal_1_1_syncable_currency.html", "class_cloud_once_1_1_internal_1_1_syncable_currency" ],
    [ "SyncableItem", "class_cloud_once_1_1_internal_1_1_syncable_item.html", "class_cloud_once_1_1_internal_1_1_syncable_item" ],
    [ "SyncableItemMetaData", "class_cloud_once_1_1_internal_1_1_syncable_item_meta_data.html", "class_cloud_once_1_1_internal_1_1_syncable_item_meta_data" ],
    [ "UnexpectedCollectionElementTypeException", "class_cloud_once_1_1_internal_1_1_unexpected_collection_element_type_exception.html", "class_cloud_once_1_1_internal_1_1_unexpected_collection_element_type_exception" ],
    [ "UnifiedAchievement", "class_cloud_once_1_1_internal_1_1_unified_achievement.html", "class_cloud_once_1_1_internal_1_1_unified_achievement" ],
    [ "UnifiedLeaderboard", "class_cloud_once_1_1_internal_1_1_unified_leaderboard.html", "class_cloud_once_1_1_internal_1_1_unified_leaderboard" ]
];